# Loc: ~/.config/alacritty/alacritty.toml

[font]
size = 15.0
offset = { x = 0, y = 4 }

[font.normal]
family = "GohuFont11NerdFont" # ttf-gohu-nerd
style = "Regular"

[general]
import = [
    # "~/.config/alacritty/themes/themes/ayu_mirage.toml"
      "~/.config/alacritty/themes/themes/citylights.toml"
    # "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
    # "~/.config/alacritty/themes/themes/mariana.toml"
]

[window]
padding = { x = 20, y = 20 }
dynamic_padding = true